//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using System.Web;

namespace UMS.Models
{
    using System;
    using System.Collections.Generic;

    public partial class ProfilePicture
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProfilePicture()
        {
            this.UserInfoes = new HashSet<UserInfo>();
        }

        public int Picture_Id { get; set; }
        public Nullable<int> User_Id { get; set; }

        public string Filename { get; set; }

        public string Type { get; set; }
        public Nullable<int> Size { get; set; }

        public string Data { get; set; }


        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserInfo> UserInfoes { get; set; }
    }
}
